apiVersion: apps/v1
kind: Deployment
metadata:
  name: mobility
  labels:
    app: mobility
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mobility
  template:
    metadata:
      labels:
        app: mobility
    spec:
      containers:
        - name: mobility
          image: username/mobility:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5